# This workflow will install Python dependencies, install all of the supported Blender versions and run tests against all of them

name: Run CATS-Blender-Plugin tests

on:
  push:
    branches: [ "master", "development", "forked_development" ]
  pull_request:
    branches: [ "master", "development", "forked_development" ]
  schedule:
    - cron: "0 4 * * 1"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Blender versions with snap
      run: |
        sudo snap set system experimental.parallel-instances=true
        sudo snap install blender_stable --stable --classic
    - name: install cats plugin for various versions
      run: |
        mkdir -p ${HOME}/.config/blender/{4.0}/scripts/addons
        ln -s ${PWD} ${HOME}/.config/blender/4.0/scripts/addons/cats
    - name: run unit tests for all versions
      run: |
        python3 ./tests/run.py --blend=blender_stable -c True || exit 1
